### ISSUE TITLE
接taptap用户认证问题

### ISSUE THREAD

**Issue by LiuMir** [taptap/TapLogin-Unity#1]
unity项目中只接taptap用户认证
09-06 16:17:41.657 1324-1324/? E/ActivityThread: Activity com.taptap.sdk.ui.TapTapActivity has leaked ServiceConnection com.taptap.sdk.ui.g$b@1658094d that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.taptap.sdk.ui.TapTapActivity has leaked ServiceConnection com.taptap.sdk.ui.g$b@1658094d that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1774)
        at android.app.ContextImpl.bindService(ContextImpl.java:1757)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
        at com.taptap.sdk.ui.g.a(CloudGameHandler.java:74)
        at com.taptap.sdk.ui.k.b(LoginClient.java:5)
        at com.taptap.sdk.ui.j.a(LoginBlock.java:5)
        at com.taptap.sdk.ui.d.a(Block.java:6)
        at com.taptap.sdk.ui.f.a(BlockManager.java:10)
        at com.taptap.sdk.ui.f.a(BlockManager.java:5)
        at com.taptap.sdk.ui.TapTapActivity.onCreate(TapTapActivity.java:11)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by LiuMir** [comment]
需要后台配置 包名 keystore的md5值
提示太不友好了
